import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Brain, CheckCircle2, Lightbulb } from "lucide-react";
import { Card, EmptyState, PageHeader, Pill, Stat } from "@/components/app/primitives";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/app/ai")({
  component: AIInsights,
});

function AIInsights() {
  const { profile, isSuperAdmin } = useAuth();

  const ai = useQuery({
    queryKey: ["ai-insights-real", profile?.tenant_id, isSuperAdmin],
    enabled: !!profile?.tenant_id || isSuperAdmin,
    queryFn: async () => {
      const db = supabase as any;
      const [insights, recommendations, conversations, events] = await Promise.all([
        db.from("ai_insights").select("id,resident_id,module,title,summary,severity,confidence,created_at").order("created_at", { ascending: false }).limit(200),
        db.from("agent_recommendations").select("id,agent_key,title,summary,urgency,status,confidence,created_at").order("created_at", { ascending: false }).limit(200),
        db.from("agent_conversations").select("id,agent_key,title,resident_id,updated_at,created_at").order("updated_at", { ascending: false }).limit(100),
        db.from("events").select("id,title,category,severity,occurred_at").order("occurred_at", { ascending: false }).limit(100),
      ]);
      const errors = [insights, recommendations, conversations, events].map((item) => item.error?.message).filter(Boolean);
      if (errors.length) throw new Error(errors.join(" | "));
      return {
        insights: insights.data ?? [],
        recommendations: recommendations.data ?? [],
        conversations: conversations.data ?? [],
        events: events.data ?? [],
      };
    },
  });

  const openRecommendations = (ai.data?.recommendations ?? []).filter((item: any) => !["accepted", "dismissed", "completed"].includes(item.status));
  const highSeverity = (ai.data?.insights ?? []).filter((item: any) => ["critical", "high", "warning"].includes(item.severity));

  return (
    <>
      <PageHeader
        title="Care Kranich Intelligence"
        subtitle="AI insights, agent recommendations and conversations from Supabase. No predictive claims are shown without records."
        action={<Pill tone={ai.isError ? "wine" : "olive"}>{ai.isError ? "Read error" : "Live AI records"}</Pill>}
      />

      {ai.isLoading ? (
        <p className="text-sm text-muted-foreground">Loading AI records...</p>
      ) : ai.isError ? (
        <Card className="border-wine/25 bg-wine/5">
          <p className="font-medium text-wine">Could not load AI records.</p>
          <p className="mt-2 text-sm text-muted-foreground">{(ai.error as Error).message}</p>
        </Card>
      ) : (
        <>
          <div className="grid gap-4 md:grid-cols-4">
            <Stat label="Insights" value={ai.data?.insights.length ?? 0} sub="ai_insights" tone="olive" />
            <Stat label="Recommendations" value={openRecommendations.length} sub="Open agent recommendations" tone="gold" />
            <Stat label="Conversations" value={ai.data?.conversations.length ?? 0} sub="Agent conversations" tone="moss" />
            <Stat label="High severity" value={highSeverity.length} sub="Warning and above" tone="wine" />
          </div>

          <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
            <Card>
              <div className="flex items-center gap-3">
                <Brain className="h-5 w-5 text-olive" />
                <h2 className="text-xl font-semibold text-foreground">AI insights</h2>
              </div>
              {(ai.data?.insights ?? []).length === 0 ? (
                <div className="mt-5">
                  <EmptyState title="No AI insights yet" hint="Insights generated by real modules will appear here." />
                </div>
              ) : (
                <div className="mt-5 space-y-3">
                  {(ai.data?.insights ?? []).map((item: any) => (
                    <div key={item.id} className="rounded-2xl border border-border/60 bg-cream/40 p-4">
                      <div className="flex flex-wrap items-center justify-between gap-2">
                        <p className="font-medium text-foreground">{item.title}</p>
                        <Pill tone={tone(item.severity)}>{item.severity}</Pill>
                      </div>
                      <p className="mt-1 text-sm leading-6 text-muted-foreground">{item.summary}</p>
                      <p className="mt-2 text-xs text-muted-foreground">{item.module} · confidence {item.confidence ?? "-"}</p>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            <Card>
              <div className="flex items-center gap-3">
                <Lightbulb className="h-5 w-5 text-olive" />
                <h2 className="text-xl font-semibold text-foreground">Agent recommendations</h2>
              </div>
              {(ai.data?.recommendations ?? []).length === 0 ? (
                <p className="mt-5 text-sm text-muted-foreground">No agent recommendations.</p>
              ) : (
                <div className="mt-5 space-y-3">
                  {(ai.data?.recommendations ?? []).map((item: any) => (
                    <div key={item.id} className="rounded-2xl border border-border/60 bg-white/50 p-4">
                      <div className="flex flex-wrap items-center justify-between gap-2">
                        <p className="font-medium text-foreground">{item.title}</p>
                        <Pill tone={tone(item.urgency)}>{item.status}</Pill>
                      </div>
                      <p className="mt-1 text-sm leading-6 text-muted-foreground">{item.summary}</p>
                      <p className="mt-2 text-xs text-muted-foreground">{item.agent_key} · confidence {item.confidence ?? "-"}</p>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            <Card className="lg:col-span-2">
              <div className="flex items-center gap-3">
                <CheckCircle2 className="h-5 w-5 text-olive" />
                <h2 className="text-xl font-semibold text-foreground">Agent conversations</h2>
              </div>
              <div className="mt-4 grid gap-3 md:grid-cols-2">
                {(ai.data?.conversations ?? []).map((item: any) => (
                  <div key={item.id} className="rounded-2xl border border-border/60 bg-cream/40 p-4">
                    <p className="font-medium text-foreground">{item.title ?? item.agent_key}</p>
                    <p className="mt-1 text-xs text-muted-foreground">{new Date(item.updated_at).toLocaleString()}</p>
                  </div>
                ))}
                {(ai.data?.conversations ?? []).length === 0 && <p className="text-sm text-muted-foreground">No agent conversations yet.</p>}
              </div>
            </Card>
          </div>
        </>
      )}
    </>
  );
}

function tone(value: string | null | undefined): "moss" | "wine" | "gold" | "muted" {
  const status = String(value ?? "").toLowerCase();
  if (["critical", "high", "urgent"].includes(status)) return "wine";
  if (["warning", "medium", "normal"].includes(status)) return "gold";
  if (["low", "info", "resolved", "accepted"].includes(status)) return "moss";
  return "muted";
}
