/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppTelemedicineRouteImport } from './routes/app.telemedicine'
import { Route as AppSmartHomeRouteImport } from './routes/app.smart-home'
import { Route as AppResidentsRouteImport } from './routes/app.residents'
import { Route as AppQualityRouteImport } from './routes/app.quality'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppMedicalRouteImport } from './routes/app.medical'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppLongevityRouteImport } from './routes/app.longevity'
import { Route as AppEmergencyRouteImport } from './routes/app.emergency'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCommandRouteImport } from './routes/app.command'
import { Route as AppCaregiverRouteImport } from './routes/app.caregiver'
import { Route as AppCarePlanRouteImport } from './routes/app.care-plan'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAcademyRouteImport } from './routes/app.academy'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemedicineRoute = AppTelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartHomeRoute = AppSmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentsRoute = AppResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLongevityRoute = AppLongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppCaregiverRoute = AppCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AppRoute,
} as any)
const AppCarePlanRoute = AppCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/command': typeof AppCommandRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/command': typeof AppCommandRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/command': typeof AppCommandRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/academy'
    | '/app/admin'
    | '/app/ai'
    | '/app/alerts'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/command'
    | '/app/documents'
    | '/app/emergency'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/memory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/residents'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/workflows'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/academy'
    | '/app/admin'
    | '/app/ai'
    | '/app/alerts'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/command'
    | '/app/documents'
    | '/app/emergency'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/memory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/residents'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/workflows'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/academy'
    | '/app/admin'
    | '/app/ai'
    | '/app/alerts'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/command'
    | '/app/documents'
    | '/app/emergency'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/memory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/residents'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/workflows'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/telemedicine': {
      id: '/app/telemedicine'
      path: '/telemedicine'
      fullPath: '/app/telemedicine'
      preLoaderRoute: typeof AppTelemedicineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smart-home': {
      id: '/app/smart-home'
      path: '/smart-home'
      fullPath: '/app/smart-home'
      preLoaderRoute: typeof AppSmartHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/residents': {
      id: '/app/residents'
      path: '/residents'
      fullPath: '/app/residents'
      preLoaderRoute: typeof AppResidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quality': {
      id: '/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medical': {
      id: '/app/medical'
      path: '/medical'
      fullPath: '/app/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/longevity': {
      id: '/app/longevity'
      path: '/longevity'
      fullPath: '/app/longevity'
      preLoaderRoute: typeof AppLongevityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emergency': {
      id: '/app/emergency'
      path: '/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/command': {
      id: '/app/command'
      path: '/command'
      fullPath: '/app/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caregiver': {
      id: '/app/caregiver'
      path: '/caregiver'
      fullPath: '/app/caregiver'
      preLoaderRoute: typeof AppCaregiverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/care-plan': {
      id: '/app/care-plan'
      path: '/care-plan'
      fullPath: '/app/care-plan'
      preLoaderRoute: typeof AppCarePlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academy': {
      id: '/app/academy'
      path: '/academy'
      fullPath: '/app/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppCarePlanRoute: typeof AppCarePlanRoute
  AppCaregiverRoute: typeof AppCaregiverRoute
  AppCommandRoute: typeof AppCommandRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppLongevityRoute: typeof AppLongevityRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQualityRoute: typeof AppQualityRoute
  AppResidentsRoute: typeof AppResidentsRoute
  AppSmartHomeRoute: typeof AppSmartHomeRoute
  AppTelemedicineRoute: typeof AppTelemedicineRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRoute,
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppCarePlanRoute: AppCarePlanRoute,
  AppCaregiverRoute: AppCaregiverRoute,
  AppCommandRoute: AppCommandRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppLongevityRoute: AppLongevityRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQualityRoute: AppQualityRoute,
  AppResidentsRoute: AppResidentsRoute,
  AppSmartHomeRoute: AppSmartHomeRoute,
  AppTelemedicineRoute: AppTelemedicineRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
