/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TelemedicineRouteImport } from './routes/telemedicine'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SmartHomeRouteImport } from './routes/smart-home'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyComplianceRouteImport } from './routes/privacy-compliance'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MedicalOfficeRouteImport } from './routes/medical-office'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilyCenterRouteImport } from './routes/family-center'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CaregiverAppRouteImport } from './routes/caregiver-app'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamesIndexRouteImport } from './routes/exames.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SolutionsSeniorLivingRouteImport } from './routes/solutions.senior-living'
import { Route as SolutionsInsuranceRouteImport } from './routes/solutions.insurance'
import { Route as SolutionsHospitalsRouteImport } from './routes/solutions.hospitals'
import { Route as SolutionsHomeCareRouteImport } from './routes/solutions.home-care'
import { Route as SolutionsClinicsRouteImport } from './routes/solutions.clinics'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as OrigensTokenRouteImport } from './routes/origens.$token'
import { Route as ExamesSlugRouteImport } from './routes/exames.$slug'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppUnitsRouteImport } from './routes/app.units'
import { Route as AppTwinRouteImport } from './routes/app.twin'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppTelemedicineRouteImport } from './routes/app.telemedicine'
import { Route as AppSmartHomeRouteImport } from './routes/app.smart-home'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppResidentsRouteImport } from './routes/app.residents'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRecordsRouteImport } from './routes/app.records'
import { Route as AppReceptionRouteImport } from './routes/app.reception'
import { Route as AppQualityRouteImport } from './routes/app.quality'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppPatientsRouteImport } from './routes/app.patients'
import { Route as AppPatientPortalRouteImport } from './routes/app.patient-portal'
import { Route as AppOriginsRouteImport } from './routes/app.origins'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppMedicationsRouteImport } from './routes/app.medications'
import { Route as AppMedicalRouteImport } from './routes/app.medical'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppLongevityRouteImport } from './routes/app.longevity'
import { Route as AppLabDashboardRouteImport } from './routes/app.lab-dashboard'
import { Route as AppLabRouteImport } from './routes/app.lab'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppIdentityRouteImport } from './routes/app.identity'
import { Route as AppHomeCollectionRouteImport } from './routes/app.home-collection'
import { Route as AppGeriatricsRouteImport } from './routes/app.geriatrics'
import { Route as AppGeneticsRouteImport } from './routes/app.genetics'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppEquipmentRouteImport } from './routes/app.equipment'
import { Route as AppEmergencyRouteImport } from './routes/app.emergency'
import { Route as AppEmailMarketingRouteImport } from './routes/app.email-marketing'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDoctorRouteImport } from './routes/app.doctor'
import { Route as AppContractsRouteImport } from './routes/app.contracts'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppCommandRouteImport } from './routes/app.command'
import { Route as AppCognitiveRouteImport } from './routes/app.cognitive'
import { Route as AppCmsRouteImport } from './routes/app.cms'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppCaregiverRouteImport } from './routes/app.caregiver'
import { Route as AppCarePlanRouteImport } from './routes/app.care-plan'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppBiRouteImport } from './routes/app.bi'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAncestryStudioRouteImport } from './routes/app.ancestry-studio'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAcademyRouteImport } from './routes/app.academy'
import { Route as AppAgentsRecommendationsRouteImport } from './routes/app.agents.recommendations'
import { Route as AppAgentsAgentKeyRouteImport } from './routes/app.agents.$agentKey'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineRoute = TelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeRoute = SmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyComplianceRoute = PrivacyComplianceRouteImport.update({
  id: '/privacy-compliance',
  path: '/privacy-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalOfficeRoute = MedicalOfficeRouteImport.update({
  id: '/medical-office',
  path: '/medical-office',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyCenterRoute = FamilyCenterRouteImport.update({
  id: '/family-center',
  path: '/family-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverAppRoute = CaregiverAppRouteImport.update({
  id: '/caregiver-app',
  path: '/caregiver-app',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesIndexRoute = ExamesIndexRouteImport.update({
  id: '/exames/',
  path: '/exames/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SolutionsSeniorLivingRoute = SolutionsSeniorLivingRouteImport.update({
  id: '/senior-living',
  path: '/senior-living',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsInsuranceRoute = SolutionsInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsHospitalsRoute = SolutionsHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsHomeCareRoute = SolutionsHomeCareRouteImport.update({
  id: '/home-care',
  path: '/home-care',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsClinicsRoute = SolutionsClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => SolutionsRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigensTokenRoute = OrigensTokenRouteImport.update({
  id: '/origens/$token',
  path: '/origens/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesSlugRoute = ExamesSlugRouteImport.update({
  id: '/exames/$slug',
  path: '/exames/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppTwinRoute = AppTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemedicineRoute = AppTelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartHomeRoute = AppSmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentsRoute = AppResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionRoute = AppReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientPortalRoute = AppPatientPortalRouteImport.update({
  id: '/patient-portal',
  path: '/patient-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppOriginsRoute = AppOriginsRouteImport.update({
  id: '/origins',
  path: '/origins',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicationsRoute = AppMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLongevityRoute = AppLongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => AppRoute,
} as any)
const AppLabDashboardRoute = AppLabDashboardRouteImport.update({
  id: '/lab-dashboard',
  path: '/lab-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeCollectionRoute = AppHomeCollectionRouteImport.update({
  id: '/home-collection',
  path: '/home-collection',
  getParentRoute: () => AppRoute,
} as any)
const AppGeriatricsRoute = AppGeriatricsRouteImport.update({
  id: '/geriatrics',
  path: '/geriatrics',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneticsRoute = AppGeneticsRouteImport.update({
  id: '/genetics',
  path: '/genetics',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailMarketingRoute = AppEmailMarketingRouteImport.update({
  id: '/email-marketing',
  path: '/email-marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppCognitiveRoute = AppCognitiveRouteImport.update({
  id: '/cognitive',
  path: '/cognitive',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsRoute = AppCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppCaregiverRoute = AppCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AppRoute,
} as any)
const AppCarePlanRoute = AppCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBiRoute = AppBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAncestryStudioRoute = AppAncestryStudioRouteImport.update({
  id: '/ancestry-studio',
  path: '/ancestry-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRecommendationsRoute =
  AppAgentsRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AppAgentsRoute,
  } as any)
const AppAgentsAgentKeyRoute = AppAgentsAgentKeyRouteImport.update({
  id: '/$agentKey',
  path: '/$agentKey',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/careers': typeof CareersRoute
  '/caregiver-app': typeof CaregiverAppRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/family-center': typeof FamilyCenterRoute
  '/login': typeof LoginRoute
  '/medical-office': typeof MedicalOfficeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-compliance': typeof PrivacyComplianceRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/smart-home': typeof SmartHomeRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ancestry-studio': typeof AppAncestryStudioRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/bi': typeof AppBiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/cms': typeof AppCmsRoute
  '/app/cognitive': typeof AppCognitiveRoute
  '/app/command': typeof AppCommandRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/doctor': typeof AppDoctorRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email-marketing': typeof AppEmailMarketingRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/exams': typeof AppExamsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/genetics': typeof AppGeneticsRoute
  '/app/geriatrics': typeof AppGeriatricsRoute
  '/app/home-collection': typeof AppHomeCollectionRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/lab': typeof AppLabRoute
  '/app/lab-dashboard': typeof AppLabDashboardRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/medications': typeof AppMedicationsRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/origins': typeof AppOriginsRoute
  '/app/patient-portal': typeof AppPatientPortalRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/reception': typeof AppReceptionRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/twin': typeof AppTwinRoute
  '/app/units': typeof AppUnitsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/exames/$slug': typeof ExamesSlugRoute
  '/origens/$token': typeof OrigensTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/solutions/clinics': typeof SolutionsClinicsRoute
  '/solutions/home-care': typeof SolutionsHomeCareRoute
  '/solutions/hospitals': typeof SolutionsHospitalsRoute
  '/solutions/insurance': typeof SolutionsInsuranceRoute
  '/solutions/senior-living': typeof SolutionsSeniorLivingRoute
  '/app/': typeof AppIndexRoute
  '/exames/': typeof ExamesIndexRoute
  '/app/agents/$agentKey': typeof AppAgentsAgentKeyRoute
  '/app/agents/recommendations': typeof AppAgentsRecommendationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/caregiver-app': typeof CaregiverAppRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/family-center': typeof FamilyCenterRoute
  '/login': typeof LoginRoute
  '/medical-office': typeof MedicalOfficeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-compliance': typeof PrivacyComplianceRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/smart-home': typeof SmartHomeRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ancestry-studio': typeof AppAncestryStudioRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/bi': typeof AppBiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/cms': typeof AppCmsRoute
  '/app/cognitive': typeof AppCognitiveRoute
  '/app/command': typeof AppCommandRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/doctor': typeof AppDoctorRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email-marketing': typeof AppEmailMarketingRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/exams': typeof AppExamsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/genetics': typeof AppGeneticsRoute
  '/app/geriatrics': typeof AppGeriatricsRoute
  '/app/home-collection': typeof AppHomeCollectionRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/lab': typeof AppLabRoute
  '/app/lab-dashboard': typeof AppLabDashboardRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/medications': typeof AppMedicationsRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/origins': typeof AppOriginsRoute
  '/app/patient-portal': typeof AppPatientPortalRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/reception': typeof AppReceptionRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/twin': typeof AppTwinRoute
  '/app/units': typeof AppUnitsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/exames/$slug': typeof ExamesSlugRoute
  '/origens/$token': typeof OrigensTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/solutions/clinics': typeof SolutionsClinicsRoute
  '/solutions/home-care': typeof SolutionsHomeCareRoute
  '/solutions/hospitals': typeof SolutionsHospitalsRoute
  '/solutions/insurance': typeof SolutionsInsuranceRoute
  '/solutions/senior-living': typeof SolutionsSeniorLivingRoute
  '/app': typeof AppIndexRoute
  '/exames': typeof ExamesIndexRoute
  '/app/agents/$agentKey': typeof AppAgentsAgentKeyRoute
  '/app/agents/recommendations': typeof AppAgentsRecommendationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/careers': typeof CareersRoute
  '/caregiver-app': typeof CaregiverAppRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/family-center': typeof FamilyCenterRoute
  '/login': typeof LoginRoute
  '/medical-office': typeof MedicalOfficeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-compliance': typeof PrivacyComplianceRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/smart-home': typeof SmartHomeRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ancestry-studio': typeof AppAncestryStudioRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/bi': typeof AppBiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/cms': typeof AppCmsRoute
  '/app/cognitive': typeof AppCognitiveRoute
  '/app/command': typeof AppCommandRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/doctor': typeof AppDoctorRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/email-marketing': typeof AppEmailMarketingRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/exams': typeof AppExamsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/genetics': typeof AppGeneticsRoute
  '/app/geriatrics': typeof AppGeriatricsRoute
  '/app/home-collection': typeof AppHomeCollectionRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/lab': typeof AppLabRoute
  '/app/lab-dashboard': typeof AppLabDashboardRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/medications': typeof AppMedicationsRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/origins': typeof AppOriginsRoute
  '/app/patient-portal': typeof AppPatientPortalRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/reception': typeof AppReceptionRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/twin': typeof AppTwinRoute
  '/app/units': typeof AppUnitsRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/exames/$slug': typeof ExamesSlugRoute
  '/origens/$token': typeof OrigensTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/solutions/clinics': typeof SolutionsClinicsRoute
  '/solutions/home-care': typeof SolutionsHomeCareRoute
  '/solutions/hospitals': typeof SolutionsHospitalsRoute
  '/solutions/insurance': typeof SolutionsInsuranceRoute
  '/solutions/senior-living': typeof SolutionsSeniorLivingRoute
  '/app/': typeof AppIndexRoute
  '/exames/': typeof ExamesIndexRoute
  '/app/agents/$agentKey': typeof AppAgentsAgentKeyRoute
  '/app/agents/recommendations': typeof AppAgentsRecommendationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/caregiver-app'
    | '/compliance'
    | '/contact'
    | '/family-center'
    | '/login'
    | '/medical-office'
    | '/onboarding'
    | '/partners'
    | '/press'
    | '/privacy'
    | '/privacy-compliance'
    | '/security'
    | '/signup'
    | '/smart-home'
    | '/solutions'
    | '/telemedicine'
    | '/terms'
    | '/app/academy'
    | '/app/admin'
    | '/app/agents'
    | '/app/ai'
    | '/app/alerts'
    | '/app/ancestry-studio'
    | '/app/approvals'
    | '/app/bi'
    | '/app/billing'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/catalog'
    | '/app/cms'
    | '/app/cognitive'
    | '/app/command'
    | '/app/companies'
    | '/app/contracts'
    | '/app/doctor'
    | '/app/documents'
    | '/app/email-marketing'
    | '/app/emergency'
    | '/app/equipment'
    | '/app/exams'
    | '/app/finance'
    | '/app/genetics'
    | '/app/geriatrics'
    | '/app/home-collection'
    | '/app/identity'
    | '/app/inbox'
    | '/app/inventory'
    | '/app/lab'
    | '/app/lab-dashboard'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/medications'
    | '/app/memory'
    | '/app/notifications'
    | '/app/orders'
    | '/app/origins'
    | '/app/patient-portal'
    | '/app/patients'
    | '/app/pos'
    | '/app/profile'
    | '/app/quality'
    | '/app/reception'
    | '/app/records'
    | '/app/reports'
    | '/app/residents'
    | '/app/schedule'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/twin'
    | '/app/units'
    | '/app/workflows'
    | '/exames/$slug'
    | '/origens/$token'
    | '/p/$slug'
    | '/solutions/clinics'
    | '/solutions/home-care'
    | '/solutions/hospitals'
    | '/solutions/insurance'
    | '/solutions/senior-living'
    | '/app/'
    | '/exames/'
    | '/app/agents/$agentKey'
    | '/app/agents/recommendations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/caregiver-app'
    | '/compliance'
    | '/contact'
    | '/family-center'
    | '/login'
    | '/medical-office'
    | '/onboarding'
    | '/partners'
    | '/press'
    | '/privacy'
    | '/privacy-compliance'
    | '/security'
    | '/signup'
    | '/smart-home'
    | '/solutions'
    | '/telemedicine'
    | '/terms'
    | '/app/academy'
    | '/app/admin'
    | '/app/agents'
    | '/app/ai'
    | '/app/alerts'
    | '/app/ancestry-studio'
    | '/app/approvals'
    | '/app/bi'
    | '/app/billing'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/catalog'
    | '/app/cms'
    | '/app/cognitive'
    | '/app/command'
    | '/app/companies'
    | '/app/contracts'
    | '/app/doctor'
    | '/app/documents'
    | '/app/email-marketing'
    | '/app/emergency'
    | '/app/equipment'
    | '/app/exams'
    | '/app/finance'
    | '/app/genetics'
    | '/app/geriatrics'
    | '/app/home-collection'
    | '/app/identity'
    | '/app/inbox'
    | '/app/inventory'
    | '/app/lab'
    | '/app/lab-dashboard'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/medications'
    | '/app/memory'
    | '/app/notifications'
    | '/app/orders'
    | '/app/origins'
    | '/app/patient-portal'
    | '/app/patients'
    | '/app/pos'
    | '/app/profile'
    | '/app/quality'
    | '/app/reception'
    | '/app/records'
    | '/app/reports'
    | '/app/residents'
    | '/app/schedule'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/twin'
    | '/app/units'
    | '/app/workflows'
    | '/exames/$slug'
    | '/origens/$token'
    | '/p/$slug'
    | '/solutions/clinics'
    | '/solutions/home-care'
    | '/solutions/hospitals'
    | '/solutions/insurance'
    | '/solutions/senior-living'
    | '/app'
    | '/exames'
    | '/app/agents/$agentKey'
    | '/app/agents/recommendations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/caregiver-app'
    | '/compliance'
    | '/contact'
    | '/family-center'
    | '/login'
    | '/medical-office'
    | '/onboarding'
    | '/partners'
    | '/press'
    | '/privacy'
    | '/privacy-compliance'
    | '/security'
    | '/signup'
    | '/smart-home'
    | '/solutions'
    | '/telemedicine'
    | '/terms'
    | '/app/academy'
    | '/app/admin'
    | '/app/agents'
    | '/app/ai'
    | '/app/alerts'
    | '/app/ancestry-studio'
    | '/app/approvals'
    | '/app/bi'
    | '/app/billing'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/catalog'
    | '/app/cms'
    | '/app/cognitive'
    | '/app/command'
    | '/app/companies'
    | '/app/contracts'
    | '/app/doctor'
    | '/app/documents'
    | '/app/email-marketing'
    | '/app/emergency'
    | '/app/equipment'
    | '/app/exams'
    | '/app/finance'
    | '/app/genetics'
    | '/app/geriatrics'
    | '/app/home-collection'
    | '/app/identity'
    | '/app/inbox'
    | '/app/inventory'
    | '/app/lab'
    | '/app/lab-dashboard'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/medications'
    | '/app/memory'
    | '/app/notifications'
    | '/app/orders'
    | '/app/origins'
    | '/app/patient-portal'
    | '/app/patients'
    | '/app/pos'
    | '/app/profile'
    | '/app/quality'
    | '/app/reception'
    | '/app/records'
    | '/app/reports'
    | '/app/residents'
    | '/app/schedule'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/twin'
    | '/app/units'
    | '/app/workflows'
    | '/exames/$slug'
    | '/origens/$token'
    | '/p/$slug'
    | '/solutions/clinics'
    | '/solutions/home-care'
    | '/solutions/hospitals'
    | '/solutions/insurance'
    | '/solutions/senior-living'
    | '/app/'
    | '/exames/'
    | '/app/agents/$agentKey'
    | '/app/agents/recommendations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  CareersRoute: typeof CareersRoute
  CaregiverAppRoute: typeof CaregiverAppRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  FamilyCenterRoute: typeof FamilyCenterRoute
  LoginRoute: typeof LoginRoute
  MedicalOfficeRoute: typeof MedicalOfficeRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyComplianceRoute: typeof PrivacyComplianceRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SmartHomeRoute: typeof SmartHomeRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TelemedicineRoute: typeof TelemedicineRoute
  TermsRoute: typeof TermsRoute
  ExamesSlugRoute: typeof ExamesSlugRoute
  OrigensTokenRoute: typeof OrigensTokenRoute
  PSlugRoute: typeof PSlugRoute
  ExamesIndexRoute: typeof ExamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine': {
      id: '/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof TelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home': {
      id: '/smart-home'
      path: '/smart-home'
      fullPath: '/smart-home'
      preLoaderRoute: typeof SmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-compliance': {
      id: '/privacy-compliance'
      path: '/privacy-compliance'
      fullPath: '/privacy-compliance'
      preLoaderRoute: typeof PrivacyComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-office': {
      id: '/medical-office'
      path: '/medical-office'
      fullPath: '/medical-office'
      preLoaderRoute: typeof MedicalOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-center': {
      id: '/family-center'
      path: '/family-center'
      fullPath: '/family-center'
      preLoaderRoute: typeof FamilyCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver-app': {
      id: '/caregiver-app'
      path: '/caregiver-app'
      fullPath: '/caregiver-app'
      preLoaderRoute: typeof CaregiverAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/': {
      id: '/exames/'
      path: '/exames'
      fullPath: '/exames/'
      preLoaderRoute: typeof ExamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/solutions/senior-living': {
      id: '/solutions/senior-living'
      path: '/senior-living'
      fullPath: '/solutions/senior-living'
      preLoaderRoute: typeof SolutionsSeniorLivingRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/insurance': {
      id: '/solutions/insurance'
      path: '/insurance'
      fullPath: '/solutions/insurance'
      preLoaderRoute: typeof SolutionsInsuranceRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/hospitals': {
      id: '/solutions/hospitals'
      path: '/hospitals'
      fullPath: '/solutions/hospitals'
      preLoaderRoute: typeof SolutionsHospitalsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/home-care': {
      id: '/solutions/home-care'
      path: '/home-care'
      fullPath: '/solutions/home-care'
      preLoaderRoute: typeof SolutionsHomeCareRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/clinics': {
      id: '/solutions/clinics'
      path: '/clinics'
      fullPath: '/solutions/clinics'
      preLoaderRoute: typeof SolutionsClinicsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origens/$token': {
      id: '/origens/$token'
      path: '/origens/$token'
      fullPath: '/origens/$token'
      preLoaderRoute: typeof OrigensTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames/$slug': {
      id: '/exames/$slug'
      path: '/exames/$slug'
      fullPath: '/exames/$slug'
      preLoaderRoute: typeof ExamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/units': {
      id: '/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/twin': {
      id: '/app/twin'
      path: '/twin'
      fullPath: '/app/twin'
      preLoaderRoute: typeof AppTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/telemedicine': {
      id: '/app/telemedicine'
      path: '/telemedicine'
      fullPath: '/app/telemedicine'
      preLoaderRoute: typeof AppTelemedicineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smart-home': {
      id: '/app/smart-home'
      path: '/smart-home'
      fullPath: '/app/smart-home'
      preLoaderRoute: typeof AppSmartHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/residents': {
      id: '/app/residents'
      path: '/residents'
      fullPath: '/app/residents'
      preLoaderRoute: typeof AppResidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/records': {
      id: '/app/records'
      path: '/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reception': {
      id: '/app/reception'
      path: '/reception'
      fullPath: '/app/reception'
      preLoaderRoute: typeof AppReceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quality': {
      id: '/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patient-portal': {
      id: '/app/patient-portal'
      path: '/patient-portal'
      fullPath: '/app/patient-portal'
      preLoaderRoute: typeof AppPatientPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/origins': {
      id: '/app/origins'
      path: '/origins'
      fullPath: '/app/origins'
      preLoaderRoute: typeof AppOriginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medications': {
      id: '/app/medications'
      path: '/medications'
      fullPath: '/app/medications'
      preLoaderRoute: typeof AppMedicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medical': {
      id: '/app/medical'
      path: '/medical'
      fullPath: '/app/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/longevity': {
      id: '/app/longevity'
      path: '/longevity'
      fullPath: '/app/longevity'
      preLoaderRoute: typeof AppLongevityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab-dashboard': {
      id: '/app/lab-dashboard'
      path: '/lab-dashboard'
      fullPath: '/app/lab-dashboard'
      preLoaderRoute: typeof AppLabDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab': {
      id: '/app/lab'
      path: '/lab'
      fullPath: '/app/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity': {
      id: '/app/identity'
      path: '/identity'
      fullPath: '/app/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home-collection': {
      id: '/app/home-collection'
      path: '/home-collection'
      fullPath: '/app/home-collection'
      preLoaderRoute: typeof AppHomeCollectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/geriatrics': {
      id: '/app/geriatrics'
      path: '/geriatrics'
      fullPath: '/app/geriatrics'
      preLoaderRoute: typeof AppGeriatricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/genetics': {
      id: '/app/genetics'
      path: '/genetics'
      fullPath: '/app/genetics'
      preLoaderRoute: typeof AppGeneticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipment': {
      id: '/app/equipment'
      path: '/equipment'
      fullPath: '/app/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emergency': {
      id: '/app/emergency'
      path: '/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email-marketing': {
      id: '/app/email-marketing'
      path: '/email-marketing'
      fullPath: '/app/email-marketing'
      preLoaderRoute: typeof AppEmailMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/doctor': {
      id: '/app/doctor'
      path: '/doctor'
      fullPath: '/app/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/command': {
      id: '/app/command'
      path: '/command'
      fullPath: '/app/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cognitive': {
      id: '/app/cognitive'
      path: '/cognitive'
      fullPath: '/app/cognitive'
      preLoaderRoute: typeof AppCognitiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms': {
      id: '/app/cms'
      path: '/cms'
      fullPath: '/app/cms'
      preLoaderRoute: typeof AppCmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caregiver': {
      id: '/app/caregiver'
      path: '/caregiver'
      fullPath: '/app/caregiver'
      preLoaderRoute: typeof AppCaregiverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/care-plan': {
      id: '/app/care-plan'
      path: '/care-plan'
      fullPath: '/app/care-plan'
      preLoaderRoute: typeof AppCarePlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bi': {
      id: '/app/bi'
      path: '/bi'
      fullPath: '/app/bi'
      preLoaderRoute: typeof AppBiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ancestry-studio': {
      id: '/app/ancestry-studio'
      path: '/ancestry-studio'
      fullPath: '/app/ancestry-studio'
      preLoaderRoute: typeof AppAncestryStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academy': {
      id: '/app/academy'
      path: '/academy'
      fullPath: '/app/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents/recommendations': {
      id: '/app/agents/recommendations'
      path: '/recommendations'
      fullPath: '/app/agents/recommendations'
      preLoaderRoute: typeof AppAgentsRecommendationsRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/app/agents/$agentKey': {
      id: '/app/agents/$agentKey'
      path: '/$agentKey'
      fullPath: '/app/agents/$agentKey'
      preLoaderRoute: typeof AppAgentsAgentKeyRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsAgentKeyRoute: typeof AppAgentsAgentKeyRoute
  AppAgentsRecommendationsRoute: typeof AppAgentsRecommendationsRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsAgentKeyRoute: AppAgentsAgentKeyRoute,
  AppAgentsRecommendationsRoute: AppAgentsRecommendationsRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAncestryStudioRoute: typeof AppAncestryStudioRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBiRoute: typeof AppBiRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCarePlanRoute: typeof AppCarePlanRoute
  AppCaregiverRoute: typeof AppCaregiverRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppCmsRoute: typeof AppCmsRoute
  AppCognitiveRoute: typeof AppCognitiveRoute
  AppCommandRoute: typeof AppCommandRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppContractsRoute: typeof AppContractsRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmailMarketingRoute: typeof AppEmailMarketingRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGeneticsRoute: typeof AppGeneticsRoute
  AppGeriatricsRoute: typeof AppGeriatricsRoute
  AppHomeCollectionRoute: typeof AppHomeCollectionRoute
  AppIdentityRoute: typeof AppIdentityRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLabRoute: typeof AppLabRoute
  AppLabDashboardRoute: typeof AppLabDashboardRoute
  AppLongevityRoute: typeof AppLongevityRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppMedicationsRoute: typeof AppMedicationsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppOriginsRoute: typeof AppOriginsRoute
  AppPatientPortalRoute: typeof AppPatientPortalRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPosRoute: typeof AppPosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQualityRoute: typeof AppQualityRoute
  AppReceptionRoute: typeof AppReceptionRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResidentsRoute: typeof AppResidentsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSmartHomeRoute: typeof AppSmartHomeRoute
  AppTelemedicineRoute: typeof AppTelemedicineRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppTwinRoute: typeof AppTwinRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRoute,
  AppAdminRoute: AppAdminRoute,
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAncestryStudioRoute: AppAncestryStudioRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBiRoute: AppBiRoute,
  AppBillingRoute: AppBillingRoute,
  AppCarePlanRoute: AppCarePlanRoute,
  AppCaregiverRoute: AppCaregiverRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppCmsRoute: AppCmsRoute,
  AppCognitiveRoute: AppCognitiveRoute,
  AppCommandRoute: AppCommandRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppContractsRoute: AppContractsRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmailMarketingRoute: AppEmailMarketingRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppExamsRoute: AppExamsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGeneticsRoute: AppGeneticsRoute,
  AppGeriatricsRoute: AppGeriatricsRoute,
  AppHomeCollectionRoute: AppHomeCollectionRoute,
  AppIdentityRoute: AppIdentityRoute,
  AppInboxRoute: AppInboxRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLabRoute: AppLabRoute,
  AppLabDashboardRoute: AppLabDashboardRoute,
  AppLongevityRoute: AppLongevityRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppMedicationsRoute: AppMedicationsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppOriginsRoute: AppOriginsRoute,
  AppPatientPortalRoute: AppPatientPortalRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPosRoute: AppPosRoute,
  AppProfileRoute: AppProfileRoute,
  AppQualityRoute: AppQualityRoute,
  AppReceptionRoute: AppReceptionRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResidentsRoute: AppResidentsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSmartHomeRoute: AppSmartHomeRoute,
  AppTelemedicineRoute: AppTelemedicineRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppTwinRoute: AppTwinRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SolutionsRouteChildren {
  SolutionsClinicsRoute: typeof SolutionsClinicsRoute
  SolutionsHomeCareRoute: typeof SolutionsHomeCareRoute
  SolutionsHospitalsRoute: typeof SolutionsHospitalsRoute
  SolutionsInsuranceRoute: typeof SolutionsInsuranceRoute
  SolutionsSeniorLivingRoute: typeof SolutionsSeniorLivingRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsClinicsRoute: SolutionsClinicsRoute,
  SolutionsHomeCareRoute: SolutionsHomeCareRoute,
  SolutionsHospitalsRoute: SolutionsHospitalsRoute,
  SolutionsInsuranceRoute: SolutionsInsuranceRoute,
  SolutionsSeniorLivingRoute: SolutionsSeniorLivingRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  CareersRoute: CareersRoute,
  CaregiverAppRoute: CaregiverAppRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  FamilyCenterRoute: FamilyCenterRoute,
  LoginRoute: LoginRoute,
  MedicalOfficeRoute: MedicalOfficeRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyComplianceRoute: PrivacyComplianceRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SmartHomeRoute: SmartHomeRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TelemedicineRoute: TelemedicineRoute,
  TermsRoute: TermsRoute,
  ExamesSlugRoute: ExamesSlugRoute,
  OrigensTokenRoute: OrigensTokenRoute,
  PSlugRoute: PSlugRoute,
  ExamesIndexRoute: ExamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
