/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TelemedicineRouteImport } from './routes/telemedicine'
import { Route as SmartHomeRouteImport } from './routes/smart-home'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyComplianceRouteImport } from './routes/privacy-compliance'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MedicalOfficeRouteImport } from './routes/medical-office'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilyCenterRouteImport } from './routes/family-center'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CaregiverAppRouteImport } from './routes/caregiver-app'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SolutionsSeniorLivingRouteImport } from './routes/solutions.senior-living'
import { Route as SolutionsInsuranceRouteImport } from './routes/solutions.insurance'
import { Route as SolutionsHospitalsRouteImport } from './routes/solutions.hospitals'
import { Route as SolutionsHomeCareRouteImport } from './routes/solutions.home-care'
import { Route as SolutionsClinicsRouteImport } from './routes/solutions.clinics'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppTelemedicineRouteImport } from './routes/app.telemedicine'
import { Route as AppSmartHomeRouteImport } from './routes/app.smart-home'
import { Route as AppResidentsRouteImport } from './routes/app.residents'
import { Route as AppQualityRouteImport } from './routes/app.quality'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppMedicalRouteImport } from './routes/app.medical'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppLongevityRouteImport } from './routes/app.longevity'
import { Route as AppEmergencyRouteImport } from './routes/app.emergency'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCommandRouteImport } from './routes/app.command'
import { Route as AppCaregiverRouteImport } from './routes/app.caregiver'
import { Route as AppCarePlanRouteImport } from './routes/app.care-plan'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAcademyRouteImport } from './routes/app.academy'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineRoute = TelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeRoute = SmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyComplianceRoute = PrivacyComplianceRouteImport.update({
  id: '/privacy-compliance',
  path: '/privacy-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalOfficeRoute = MedicalOfficeRouteImport.update({
  id: '/medical-office',
  path: '/medical-office',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyCenterRoute = FamilyCenterRouteImport.update({
  id: '/family-center',
  path: '/family-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverAppRoute = CaregiverAppRouteImport.update({
  id: '/caregiver-app',
  path: '/caregiver-app',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SolutionsSeniorLivingRoute = SolutionsSeniorLivingRouteImport.update({
  id: '/solutions/senior-living',
  path: '/solutions/senior-living',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsInsuranceRoute = SolutionsInsuranceRouteImport.update({
  id: '/solutions/insurance',
  path: '/solutions/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHospitalsRoute = SolutionsHospitalsRouteImport.update({
  id: '/solutions/hospitals',
  path: '/solutions/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsHomeCareRoute = SolutionsHomeCareRouteImport.update({
  id: '/solutions/home-care',
  path: '/solutions/home-care',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsClinicsRoute = SolutionsClinicsRouteImport.update({
  id: '/solutions/clinics',
  path: '/solutions/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemedicineRoute = AppTelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartHomeRoute = AppSmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => AppRoute,
} as any)
const AppResidentsRoute = AppResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLongevityRoute = AppLongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppCaregiverRoute = AppCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AppRoute,
} as any)
const AppCarePlanRoute = AppCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/careers': typeof CareersRoute
  '/caregiver-app': typeof CaregiverAppRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/family-center': typeof FamilyCenterRoute
  '/login': typeof LoginRoute
  '/medical-office': typeof MedicalOfficeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-compliance': typeof PrivacyComplianceRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/smart-home': typeof SmartHomeRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/command': typeof AppCommandRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/solutions/clinics': typeof SolutionsClinicsRoute
  '/solutions/home-care': typeof SolutionsHomeCareRoute
  '/solutions/hospitals': typeof SolutionsHospitalsRoute
  '/solutions/insurance': typeof SolutionsInsuranceRoute
  '/solutions/senior-living': typeof SolutionsSeniorLivingRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/caregiver-app': typeof CaregiverAppRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/family-center': typeof FamilyCenterRoute
  '/login': typeof LoginRoute
  '/medical-office': typeof MedicalOfficeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-compliance': typeof PrivacyComplianceRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/smart-home': typeof SmartHomeRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/command': typeof AppCommandRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/solutions/clinics': typeof SolutionsClinicsRoute
  '/solutions/home-care': typeof SolutionsHomeCareRoute
  '/solutions/hospitals': typeof SolutionsHospitalsRoute
  '/solutions/insurance': typeof SolutionsInsuranceRoute
  '/solutions/senior-living': typeof SolutionsSeniorLivingRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/careers': typeof CareersRoute
  '/caregiver-app': typeof CaregiverAppRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/family-center': typeof FamilyCenterRoute
  '/login': typeof LoginRoute
  '/medical-office': typeof MedicalOfficeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-compliance': typeof PrivacyComplianceRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/smart-home': typeof SmartHomeRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/caregiver': typeof AppCaregiverRoute
  '/app/command': typeof AppCommandRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/longevity': typeof AppLongevityRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/residents': typeof AppResidentsRoute
  '/app/smart-home': typeof AppSmartHomeRoute
  '/app/telemedicine': typeof AppTelemedicineRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/solutions/clinics': typeof SolutionsClinicsRoute
  '/solutions/home-care': typeof SolutionsHomeCareRoute
  '/solutions/hospitals': typeof SolutionsHospitalsRoute
  '/solutions/insurance': typeof SolutionsInsuranceRoute
  '/solutions/senior-living': typeof SolutionsSeniorLivingRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/caregiver-app'
    | '/compliance'
    | '/contact'
    | '/family-center'
    | '/login'
    | '/medical-office'
    | '/onboarding'
    | '/partners'
    | '/press'
    | '/privacy'
    | '/privacy-compliance'
    | '/security'
    | '/signup'
    | '/smart-home'
    | '/telemedicine'
    | '/terms'
    | '/app/academy'
    | '/app/admin'
    | '/app/ai'
    | '/app/alerts'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/command'
    | '/app/documents'
    | '/app/emergency'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/memory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/residents'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/workflows'
    | '/solutions/clinics'
    | '/solutions/home-care'
    | '/solutions/hospitals'
    | '/solutions/insurance'
    | '/solutions/senior-living'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/caregiver-app'
    | '/compliance'
    | '/contact'
    | '/family-center'
    | '/login'
    | '/medical-office'
    | '/onboarding'
    | '/partners'
    | '/press'
    | '/privacy'
    | '/privacy-compliance'
    | '/security'
    | '/signup'
    | '/smart-home'
    | '/telemedicine'
    | '/terms'
    | '/app/academy'
    | '/app/admin'
    | '/app/ai'
    | '/app/alerts'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/command'
    | '/app/documents'
    | '/app/emergency'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/memory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/residents'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/workflows'
    | '/solutions/clinics'
    | '/solutions/home-care'
    | '/solutions/hospitals'
    | '/solutions/insurance'
    | '/solutions/senior-living'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/careers'
    | '/caregiver-app'
    | '/compliance'
    | '/contact'
    | '/family-center'
    | '/login'
    | '/medical-office'
    | '/onboarding'
    | '/partners'
    | '/press'
    | '/privacy'
    | '/privacy-compliance'
    | '/security'
    | '/signup'
    | '/smart-home'
    | '/telemedicine'
    | '/terms'
    | '/app/academy'
    | '/app/admin'
    | '/app/ai'
    | '/app/alerts'
    | '/app/care-plan'
    | '/app/caregiver'
    | '/app/command'
    | '/app/documents'
    | '/app/emergency'
    | '/app/longevity'
    | '/app/marketplace'
    | '/app/medical'
    | '/app/memory'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/residents'
    | '/app/smart-home'
    | '/app/telemedicine'
    | '/app/tenants'
    | '/app/timeline'
    | '/app/workflows'
    | '/solutions/clinics'
    | '/solutions/home-care'
    | '/solutions/hospitals'
    | '/solutions/insurance'
    | '/solutions/senior-living'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  CareersRoute: typeof CareersRoute
  CaregiverAppRoute: typeof CaregiverAppRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  FamilyCenterRoute: typeof FamilyCenterRoute
  LoginRoute: typeof LoginRoute
  MedicalOfficeRoute: typeof MedicalOfficeRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyComplianceRoute: typeof PrivacyComplianceRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SmartHomeRoute: typeof SmartHomeRoute
  TelemedicineRoute: typeof TelemedicineRoute
  TermsRoute: typeof TermsRoute
  SolutionsClinicsRoute: typeof SolutionsClinicsRoute
  SolutionsHomeCareRoute: typeof SolutionsHomeCareRoute
  SolutionsHospitalsRoute: typeof SolutionsHospitalsRoute
  SolutionsInsuranceRoute: typeof SolutionsInsuranceRoute
  SolutionsSeniorLivingRoute: typeof SolutionsSeniorLivingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine': {
      id: '/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof TelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home': {
      id: '/smart-home'
      path: '/smart-home'
      fullPath: '/smart-home'
      preLoaderRoute: typeof SmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-compliance': {
      id: '/privacy-compliance'
      path: '/privacy-compliance'
      fullPath: '/privacy-compliance'
      preLoaderRoute: typeof PrivacyComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-office': {
      id: '/medical-office'
      path: '/medical-office'
      fullPath: '/medical-office'
      preLoaderRoute: typeof MedicalOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-center': {
      id: '/family-center'
      path: '/family-center'
      fullPath: '/family-center'
      preLoaderRoute: typeof FamilyCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver-app': {
      id: '/caregiver-app'
      path: '/caregiver-app'
      fullPath: '/caregiver-app'
      preLoaderRoute: typeof CaregiverAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/solutions/senior-living': {
      id: '/solutions/senior-living'
      path: '/solutions/senior-living'
      fullPath: '/solutions/senior-living'
      preLoaderRoute: typeof SolutionsSeniorLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/insurance': {
      id: '/solutions/insurance'
      path: '/solutions/insurance'
      fullPath: '/solutions/insurance'
      preLoaderRoute: typeof SolutionsInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/hospitals': {
      id: '/solutions/hospitals'
      path: '/solutions/hospitals'
      fullPath: '/solutions/hospitals'
      preLoaderRoute: typeof SolutionsHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/home-care': {
      id: '/solutions/home-care'
      path: '/solutions/home-care'
      fullPath: '/solutions/home-care'
      preLoaderRoute: typeof SolutionsHomeCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/clinics': {
      id: '/solutions/clinics'
      path: '/solutions/clinics'
      fullPath: '/solutions/clinics'
      preLoaderRoute: typeof SolutionsClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/telemedicine': {
      id: '/app/telemedicine'
      path: '/telemedicine'
      fullPath: '/app/telemedicine'
      preLoaderRoute: typeof AppTelemedicineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smart-home': {
      id: '/app/smart-home'
      path: '/smart-home'
      fullPath: '/app/smart-home'
      preLoaderRoute: typeof AppSmartHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/residents': {
      id: '/app/residents'
      path: '/residents'
      fullPath: '/app/residents'
      preLoaderRoute: typeof AppResidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quality': {
      id: '/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medical': {
      id: '/app/medical'
      path: '/medical'
      fullPath: '/app/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/longevity': {
      id: '/app/longevity'
      path: '/longevity'
      fullPath: '/app/longevity'
      preLoaderRoute: typeof AppLongevityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emergency': {
      id: '/app/emergency'
      path: '/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/command': {
      id: '/app/command'
      path: '/command'
      fullPath: '/app/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caregiver': {
      id: '/app/caregiver'
      path: '/caregiver'
      fullPath: '/app/caregiver'
      preLoaderRoute: typeof AppCaregiverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/care-plan': {
      id: '/app/care-plan'
      path: '/care-plan'
      fullPath: '/app/care-plan'
      preLoaderRoute: typeof AppCarePlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academy': {
      id: '/app/academy'
      path: '/academy'
      fullPath: '/app/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppCarePlanRoute: typeof AppCarePlanRoute
  AppCaregiverRoute: typeof AppCaregiverRoute
  AppCommandRoute: typeof AppCommandRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppLongevityRoute: typeof AppLongevityRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQualityRoute: typeof AppQualityRoute
  AppResidentsRoute: typeof AppResidentsRoute
  AppSmartHomeRoute: typeof AppSmartHomeRoute
  AppTelemedicineRoute: typeof AppTelemedicineRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRoute,
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppCarePlanRoute: AppCarePlanRoute,
  AppCaregiverRoute: AppCaregiverRoute,
  AppCommandRoute: AppCommandRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppLongevityRoute: AppLongevityRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQualityRoute: AppQualityRoute,
  AppResidentsRoute: AppResidentsRoute,
  AppSmartHomeRoute: AppSmartHomeRoute,
  AppTelemedicineRoute: AppTelemedicineRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  CareersRoute: CareersRoute,
  CaregiverAppRoute: CaregiverAppRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  FamilyCenterRoute: FamilyCenterRoute,
  LoginRoute: LoginRoute,
  MedicalOfficeRoute: MedicalOfficeRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyComplianceRoute: PrivacyComplianceRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SmartHomeRoute: SmartHomeRoute,
  TelemedicineRoute: TelemedicineRoute,
  TermsRoute: TermsRoute,
  SolutionsClinicsRoute: SolutionsClinicsRoute,
  SolutionsHomeCareRoute: SolutionsHomeCareRoute,
  SolutionsHospitalsRoute: SolutionsHospitalsRoute,
  SolutionsInsuranceRoute: SolutionsInsuranceRoute,
  SolutionsSeniorLivingRoute: SolutionsSeniorLivingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
